Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -16,22 +16,22 @@ jobs:
           DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_EMAIL }}" --password-stdin
-      
+
       - name: Build Docker image
-        run: docker build -t emartbackend/e-com .
-      
+        run: docker build -t emartbackend/e-com ../
+
       - name: Publish image to Docker Hub
         run: docker push emartbackend/e-com:latest
 
   deploy:
     needs: build
-    runs-on: self-hosted  # Ensure your self-hosted runner is properly set up
+    runs-on: self-hosted # Ensure your self-hosted runner is properly set up
     steps:
       - name: Pull image from Docker Hub
         run: docker pull emartbackend/e-com:latest
-      
+
       - name: Delete old container
-        run: docker rm -f e-com-container || true  # Avoid failure if the container does not exist
-      
+        run: docker rm -f e-com-container || true # Avoid failure if the container does not exist
+
       - name: Run Docker container
         run: docker run -d -p 5000:5000 --name e-com-container emartbackend/e-com:latest
