changes in work flow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -6,24 +6,32 @@ on:
 
 jobs:
   build:
-    runs-on: [ubuntu-latest]
+    runs-on: ubuntu-latest
     steps:
-      - name: checkout source
+      - name: Checkout source
         uses: actions/checkout@v3
-      - name: login to docker hub
-        run: docker login -u "Ravi@13012" -p "Ravi@1306"
-      - name: Build docker image
-        run: docker build -t emartbackend/nodejs-app .
-      - name: Publish image to docker hub
-        run: docker push emartbackend/nodejs-app:latest
+
+      - name: Login to Docker Hub
+        env:
+          DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_EMAIL }}" --password-stdin
+
+      - name: Build Docker image
+        run: docker build -t emartbackend/e-com .
+
+      - name: Publish image to Docker Hub
+        run: docker push emartbackend/e-com:latest
 
   deploy:
     needs: build
-    runs-on: [aws-ec2]
+    runs-on: self-hosted # Ensure your self-hosted runner is properly set up
     steps:
-      - name: Pull image from docker hub
-        run: docker pull emartbackend/nodejs-app:latest
-      - name: Delete old contaiiner
-        run: docker rm -f nodejs-app-container
-      - name: Run docker container
-        run: docker run -d -p 5000:5000 -name nodejs-app-container emartbackend/nodejs-app:latest
+      - name: Pull image from Docker Hub
+        run: docker pull emartbackend/e-com:latest
+
+      - name: Delete old container
+        run: docker rm -f e-com-container || true # Avoid failure if the container does not exist
+
+      - name: Run Docker container
+        run: docker run -d -p 5000:5000 --name e-com-container emartbackend/e-com:latest
